"""add company and listing lifecycle events

Revision ID: 078715b21fb3
Revises: 1a57c91941f6
Create Date: 2026-09-20 22:14:42.457075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '078715b21fb3'
down_revision: Union[str, Sequence[str], None] = '1a57c91941f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_relationships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_company_id', sa.Uuid(), nullable=False),
    sa.Column('target_company_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('relationship_type', sa.String(length=40), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('known_date', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("relationship_type IN ('merged_into', 'acquired_by', 'spun_off_into', 'successor_of')", name='ck_company_relationship_type'),
    sa.CheckConstraint('source_company_id <> target_company_id', name='ck_company_relationship_different_companies'),
    sa.ForeignKeyConstraint(['source_company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['target_company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_company_id', 'target_company_id', 'source_id', 'relationship_type', 'effective_date', name='uq_company_relationship')
    )
    op.create_index(op.f('ix_company_relationships_effective_date'), 'company_relationships', ['effective_date'], unique=False)
    op.create_index(op.f('ix_company_relationships_known_date'), 'company_relationships', ['known_date'], unique=False)
    op.create_index(op.f('ix_company_relationships_relationship_type'), 'company_relationships', ['relationship_type'], unique=False)
    op.create_index(op.f('ix_company_relationships_source_company_id'), 'company_relationships', ['source_company_id'], unique=False)
    op.create_index(op.f('ix_company_relationships_source_id'), 'company_relationships', ['source_id'], unique=False)
    op.create_index(op.f('ix_company_relationships_target_company_id'), 'company_relationships', ['target_company_id'], unique=False)
    op.create_table('listing_lifecycle_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('listing_id', sa.Uuid(), nullable=False),
    sa.Column('successor_listing_id', sa.Uuid(), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('known_date', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("event_type IN ('ticker_change', 'exchange_change', 'delisting', 'relisting')", name='ck_listing_lifecycle_event_type'),
    sa.CheckConstraint('successor_listing_id IS NULL OR successor_listing_id <> listing_id', name='ck_listing_event_different_successor'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['successor_listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id', 'source_id', 'event_type', 'effective_date', name='uq_listing_lifecycle_event')
    )
    op.create_index(op.f('ix_listing_lifecycle_events_effective_date'), 'listing_lifecycle_events', ['effective_date'], unique=False)
    op.create_index(op.f('ix_listing_lifecycle_events_event_type'), 'listing_lifecycle_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_listing_lifecycle_events_known_date'), 'listing_lifecycle_events', ['known_date'], unique=False)
    op.create_index(op.f('ix_listing_lifecycle_events_listing_id'), 'listing_lifecycle_events', ['listing_id'], unique=False)
    op.create_index(op.f('ix_listing_lifecycle_events_source_id'), 'listing_lifecycle_events', ['source_id'], unique=False)
    op.create_index(op.f('ix_listing_lifecycle_events_successor_listing_id'), 'listing_lifecycle_events', ['successor_listing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listing_lifecycle_events_successor_listing_id'), table_name='listing_lifecycle_events')
    op.drop_index(op.f('ix_listing_lifecycle_events_source_id'), table_name='listing_lifecycle_events')
    op.drop_index(op.f('ix_listing_lifecycle_events_listing_id'), table_name='listing_lifecycle_events')
    op.drop_index(op.f('ix_listing_lifecycle_events_known_date'), table_name='listing_lifecycle_events')
    op.drop_index(op.f('ix_listing_lifecycle_events_event_type'), table_name='listing_lifecycle_events')
    op.drop_index(op.f('ix_listing_lifecycle_events_effective_date'), table_name='listing_lifecycle_events')
    op.drop_table('listing_lifecycle_events')
    op.drop_index(op.f('ix_company_relationships_target_company_id'), table_name='company_relationships')
    op.drop_index(op.f('ix_company_relationships_source_id'), table_name='company_relationships')
    op.drop_index(op.f('ix_company_relationships_source_company_id'), table_name='company_relationships')
    op.drop_index(op.f('ix_company_relationships_relationship_type'), table_name='company_relationships')
    op.drop_index(op.f('ix_company_relationships_known_date'), table_name='company_relationships')
    op.drop_index(op.f('ix_company_relationships_effective_date'), table_name='company_relationships')
    op.drop_table('company_relationships')
    # ### end Alembic commands ###
