"""add external identity resolution

Revision ID: 1a57c91941f6
Revises: 8283d03a730d
Create Date: 2026-09-20 21:55:25.208028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a57c91941f6'
down_revision: Union[str, Sequence[str], None] = '8283d03a730d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_aliases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('alias_type', sa.String(length=40), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from', name='ck_company_alias_dates'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'alias', 'valid_from', name='uq_company_alias')
    )
    op.create_index(op.f('ix_company_aliases_alias'), 'company_aliases', ['alias'], unique=False)
    op.create_index(op.f('ix_company_aliases_company_id'), 'company_aliases', ['company_id'], unique=False)
    op.create_table('company_identifiers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('scheme', sa.String(length=40), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from', name='ck_company_identifier_dates'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheme', 'value', 'valid_from', name='uq_company_identifier_value')
    )
    op.create_index(op.f('ix_company_identifiers_company_id'), 'company_identifiers', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_identifiers_scheme'), 'company_identifiers', ['scheme'], unique=False)
    op.create_index(op.f('ix_company_identifiers_value'), 'company_identifiers', ['value'], unique=False)
    op.create_table('security_identifiers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('security_id', sa.Uuid(), nullable=False),
    sa.Column('scheme', sa.String(length=40), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from', name='ck_security_identifier_dates'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheme', 'value', 'valid_from', name='uq_security_identifier_value')
    )
    op.create_index(op.f('ix_security_identifiers_scheme'), 'security_identifiers', ['scheme'], unique=False)
    op.create_index(op.f('ix_security_identifiers_security_id'), 'security_identifiers', ['security_id'], unique=False)
    op.create_index(op.f('ix_security_identifiers_value'), 'security_identifiers', ['value'], unique=False)
    op.create_table('listing_provider_symbols',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('listing_id', sa.Uuid(), nullable=False),
    sa.Column('provider_name', sa.String(length=80), nullable=False),
    sa.Column('symbol', sa.String(length=80), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from', name='ck_provider_symbol_dates'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id', 'provider_name', 'symbol', 'valid_from', name='uq_listing_provider_symbol')
    )
    op.create_index(op.f('ix_listing_provider_symbols_listing_id'), 'listing_provider_symbols', ['listing_id'], unique=False)
    op.create_index(op.f('ix_listing_provider_symbols_provider_name'), 'listing_provider_symbols', ['provider_name'], unique=False)
    op.create_index(op.f('ix_listing_provider_symbols_symbol'), 'listing_provider_symbols', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listing_provider_symbols_symbol'), table_name='listing_provider_symbols')
    op.drop_index(op.f('ix_listing_provider_symbols_provider_name'), table_name='listing_provider_symbols')
    op.drop_index(op.f('ix_listing_provider_symbols_listing_id'), table_name='listing_provider_symbols')
    op.drop_table('listing_provider_symbols')
    op.drop_index(op.f('ix_security_identifiers_value'), table_name='security_identifiers')
    op.drop_index(op.f('ix_security_identifiers_security_id'), table_name='security_identifiers')
    op.drop_index(op.f('ix_security_identifiers_scheme'), table_name='security_identifiers')
    op.drop_table('security_identifiers')
    op.drop_index(op.f('ix_company_identifiers_value'), table_name='company_identifiers')
    op.drop_index(op.f('ix_company_identifiers_scheme'), table_name='company_identifiers')
    op.drop_index(op.f('ix_company_identifiers_company_id'), table_name='company_identifiers')
    op.drop_table('company_identifiers')
    op.drop_index(op.f('ix_company_aliases_company_id'), table_name='company_aliases')
    op.drop_index(op.f('ix_company_aliases_alias'), table_name='company_aliases')
    op.drop_table('company_aliases')
    # ### end Alembic commands ###
