"""add raw data archive and quality issues

Revision ID: 27b612bf5a8f
Revises: 80c65da572a2
Create Date: 2026-09-11 23:03:14.821933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27b612bf5a8f'
down_revision: Union[str, Sequence[str], None] = '80c65da572a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_quality_issues',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ingestion_run_id', sa.Uuid(), nullable=False),
    sa.Column('listing_id', sa.Uuid(), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('rule_code', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_quality_issues_ingestion_run_id'), 'data_quality_issues', ['ingestion_run_id'], unique=False)
    op.create_index(op.f('ix_data_quality_issues_listing_id'), 'data_quality_issues', ['listing_id'], unique=False)
    op.create_table('raw_data_artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ingestion_run_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('listing_id', sa.Uuid(), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('byte_count', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_data_artifacts_ingestion_run_id'), 'raw_data_artifacts', ['ingestion_run_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_data_artifacts_ingestion_run_id'), table_name='raw_data_artifacts')
    op.drop_table('raw_data_artifacts')
    op.drop_index(op.f('ix_data_quality_issues_listing_id'), table_name='data_quality_issues')
    op.drop_index(op.f('ix_data_quality_issues_ingestion_run_id'), table_name='data_quality_issues')
    op.drop_table('data_quality_issues')
    # ### end Alembic commands ###
