"""add corporate action storage

Revision ID: 28ae8129b539
Revises: 55bd469d156f
Create Date: 2026-09-16 23:56:45.207433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28ae8129b539'
down_revision: Union[str, Sequence[str], None] = '55bd469d156f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dividends',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('listing_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('last_ingestion_run_id', sa.Uuid(), nullable=False),
    sa.Column('ex_dividend_date', sa.Date(), nullable=False),
    sa.Column('declaration_date', sa.Date(), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_dividend_non_negative_amount'),
    sa.ForeignKeyConstraint(['last_ingestion_run_id'], ['ingestion_runs.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id', 'source_id', 'ex_dividend_date', 'amount', name='uq_dividend_listing_source_event')
    )
    op.create_index(op.f('ix_dividends_ex_dividend_date'), 'dividends', ['ex_dividend_date'], unique=False)
    op.create_index(op.f('ix_dividends_listing_id'), 'dividends', ['listing_id'], unique=False)
    op.create_index(op.f('ix_dividends_source_id'), 'dividends', ['source_id'], unique=False)
    op.create_table('stock_splits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('listing_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('last_ingestion_run_id', sa.Uuid(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('split_factor', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('split_factor > 0', name='ck_stock_split_positive_factor'),
    sa.ForeignKeyConstraint(['last_ingestion_run_id'], ['ingestion_runs.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id', 'source_id', 'effective_date', name='uq_split_listing_source_date')
    )
    op.create_index(op.f('ix_stock_splits_effective_date'), 'stock_splits', ['effective_date'], unique=False)
    op.create_index(op.f('ix_stock_splits_listing_id'), 'stock_splits', ['listing_id'], unique=False)
    op.create_index(op.f('ix_stock_splits_source_id'), 'stock_splits', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_splits_source_id'), table_name='stock_splits')
    op.drop_index(op.f('ix_stock_splits_listing_id'), table_name='stock_splits')
    op.drop_index(op.f('ix_stock_splits_effective_date'), table_name='stock_splits')
    op.drop_table('stock_splits')
    op.drop_index(op.f('ix_dividends_source_id'), table_name='dividends')
    op.drop_index(op.f('ix_dividends_listing_id'), table_name='dividends')
    op.drop_index(op.f('ix_dividends_ex_dividend_date'), table_name='dividends')
    op.drop_table('dividends')
    # ### end Alembic commands ###
