"""add shares fx and market cap foundation

Revision ID: 3bbb39cee74d
Revises: 28ae8129b539
Create Date: 2026-09-17 01:24:56.405914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bbb39cee74d'
down_revision: Union[str, Sequence[str], None] = '28ae8129b539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fx_rates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('quote_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('base_currency <> quote_currency', name='ck_fx_different_currencies'),
    sa.CheckConstraint('rate > 0', name='ck_fx_rate_positive'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'rate_date', 'base_currency', 'quote_currency', name='uq_fx_rate')
    )
    op.create_index(op.f('ix_fx_rates_rate_date'), 'fx_rates', ['rate_date'], unique=False)
    op.create_index(op.f('ix_fx_rates_source_id'), 'fx_rates', ['source_id'], unique=False)
    op.create_table('shares_outstanding_observations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('security_id', sa.Uuid(), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('known_date', sa.Date(), nullable=False),
    sa.Column('shares_outstanding', sa.Numeric(precision=30, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('known_date >= observation_date', name='ck_shares_known_after_observation'),
    sa.CheckConstraint('shares_outstanding > 0', name='ck_shares_outstanding_positive'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'security_id', 'source_id', 'observation_date', 'known_date', name='uq_shares_observation')
    )
    op.create_index(op.f('ix_shares_outstanding_observations_company_id'), 'shares_outstanding_observations', ['company_id'], unique=False)
    op.create_index(op.f('ix_shares_outstanding_observations_known_date'), 'shares_outstanding_observations', ['known_date'], unique=False)
    op.create_index(op.f('ix_shares_outstanding_observations_observation_date'), 'shares_outstanding_observations', ['observation_date'], unique=False)
    op.create_index(op.f('ix_shares_outstanding_observations_security_id'), 'shares_outstanding_observations', ['security_id'], unique=False)
    op.create_index(op.f('ix_shares_outstanding_observations_source_id'), 'shares_outstanding_observations', ['source_id'], unique=False)
    op.create_table('market_cap_observations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('listing_id', sa.Uuid(), nullable=False),
    sa.Column('valuation_date', sa.Date(), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('shares_observation_id', sa.Uuid(), nullable=False),
    sa.Column('fx_rate_id', sa.Uuid(), nullable=True),
    sa.Column('local_currency', sa.String(length=3), nullable=False),
    sa.Column('price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('shares_outstanding', sa.Numeric(precision=30, scale=4), nullable=False),
    sa.Column('local_market_cap', sa.Numeric(precision=38, scale=4), nullable=False),
    sa.Column('market_cap_usd', sa.Numeric(precision=38, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('local_market_cap > 0', name='ck_local_market_cap_positive'),
    sa.CheckConstraint('market_cap_usd > 0', name='ck_market_cap_usd_positive'),
    sa.CheckConstraint('price > 0', name='ck_market_cap_price_positive'),
    sa.CheckConstraint('shares_outstanding > 0', name='ck_market_cap_shares_positive'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['fx_rate_id'], ['fx_rates.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['shares_observation_id'], ['shares_outstanding_observations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'listing_id', 'valuation_date', name='uq_market_cap_valuation')
    )
    op.create_index(op.f('ix_market_cap_observations_company_id'), 'market_cap_observations', ['company_id'], unique=False)
    op.create_index(op.f('ix_market_cap_observations_listing_id'), 'market_cap_observations', ['listing_id'], unique=False)
    op.create_index(op.f('ix_market_cap_observations_market_cap_usd'), 'market_cap_observations', ['market_cap_usd'], unique=False)
    op.create_index(op.f('ix_market_cap_observations_valuation_date'), 'market_cap_observations', ['valuation_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_cap_observations_valuation_date'), table_name='market_cap_observations')
    op.drop_index(op.f('ix_market_cap_observations_market_cap_usd'), table_name='market_cap_observations')
    op.drop_index(op.f('ix_market_cap_observations_listing_id'), table_name='market_cap_observations')
    op.drop_index(op.f('ix_market_cap_observations_company_id'), table_name='market_cap_observations')
    op.drop_table('market_cap_observations')
    op.drop_index(op.f('ix_shares_outstanding_observations_source_id'), table_name='shares_outstanding_observations')
    op.drop_index(op.f('ix_shares_outstanding_observations_security_id'), table_name='shares_outstanding_observations')
    op.drop_index(op.f('ix_shares_outstanding_observations_observation_date'), table_name='shares_outstanding_observations')
    op.drop_index(op.f('ix_shares_outstanding_observations_known_date'), table_name='shares_outstanding_observations')
    op.drop_index(op.f('ix_shares_outstanding_observations_company_id'), table_name='shares_outstanding_observations')
    op.drop_table('shares_outstanding_observations')
    op.drop_index(op.f('ix_fx_rates_source_id'), table_name='fx_rates')
    op.drop_index(op.f('ix_fx_rates_rate_date'), table_name='fx_rates')
    op.drop_table('fx_rates')
    # ### end Alembic commands ###
