"""add batch retrieval retry and throttle state

Revision ID: 55bd469d156f
Revises: 8f52c1c99ae7
Create Date: 2026-09-13 01:28:15.393422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55bd469d156f'
down_revision: Union[str, Sequence[str], None] = '8f52c1c99ae7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_throttle_states',
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('quota_date', sa.Date(), nullable=False),
    sa.Column('requests_today', sa.Integer(), nullable=False),
    sa.Column('last_request_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('blocked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('block_reason', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('provider_name')
    )
    op.create_table('retrieval_batch_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tracking_run_id', sa.Uuid(), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('requested_limit', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('attempts_started', sa.Integer(), nullable=False),
    sa.Column('jobs_completed', sa.Integer(), nullable=False),
    sa.Column('retry_scheduled', sa.Integer(), nullable=False),
    sa.Column('jobs_failed', sa.Integer(), nullable=False),
    sa.Column('paused_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stop_reason', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tracking_run_id'], ['tracking_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retrieval_batch_runs_status'), 'retrieval_batch_runs', ['status'], unique=False)
    op.create_index(op.f('ix_retrieval_batch_runs_tracking_run_id'), 'retrieval_batch_runs', ['tracking_run_id'], unique=False)
    op.create_table('retrieval_job_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('batch_run_id', sa.Uuid(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error_type', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['batch_run_id'], ['retrieval_batch_runs.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['retrieval_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'attempt_number', name='uq_retrieval_job_attempt')
    )
    op.create_index(op.f('ix_retrieval_job_attempts_batch_run_id'), 'retrieval_job_attempts', ['batch_run_id'], unique=False)
    op.create_index(op.f('ix_retrieval_job_attempts_job_id'), 'retrieval_job_attempts', ['job_id'], unique=False)
    op.add_column('retrieval_jobs', sa.Column('last_error_type', sa.String(length=50), nullable=True))
    op.add_column('retrieval_jobs', sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('retrieval_jobs', sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_retrieval_jobs_next_retry_at'), 'retrieval_jobs', ['next_retry_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retrieval_jobs_next_retry_at'), table_name='retrieval_jobs')
    op.drop_column('retrieval_jobs', 'next_retry_at')
    op.drop_column('retrieval_jobs', 'last_attempt_at')
    op.drop_column('retrieval_jobs', 'last_error_type')
    op.drop_index(op.f('ix_retrieval_job_attempts_job_id'), table_name='retrieval_job_attempts')
    op.drop_index(op.f('ix_retrieval_job_attempts_batch_run_id'), table_name='retrieval_job_attempts')
    op.drop_table('retrieval_job_attempts')
    op.drop_index(op.f('ix_retrieval_batch_runs_tracking_run_id'), table_name='retrieval_batch_runs')
    op.drop_index(op.f('ix_retrieval_batch_runs_status'), table_name='retrieval_batch_runs')
    op.drop_table('retrieval_batch_runs')
    op.drop_table('provider_throttle_states')
    # ### end Alembic commands ###
