"""add market data storage

Revision ID: 80c65da572a2
Revises: d236eb6c89f0
Create Date: 2026-09-11 22:54:06.263606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80c65da572a2'
down_revision: Union[str, Sequence[str], None] = 'd236eb6c89f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('dataset_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_name', 'dataset_name', name='uq_data_source_provider_dataset')
    )
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('listing_id', sa.Uuid(), nullable=False),
    sa.Column('requested_symbol', sa.String(length=32), nullable=False),
    sa.Column('full_history', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('rows_received', sa.Integer(), nullable=False),
    sa.Column('rows_inserted', sa.Integer(), nullable=False),
    sa.Column('rows_updated', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_runs_listing_id'), 'ingestion_runs', ['listing_id'], unique=False)
    op.create_index(op.f('ix_ingestion_runs_source_id'), 'ingestion_runs', ['source_id'], unique=False)
    op.create_table('daily_price_bars',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('listing_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('last_ingestion_run_id', sa.Uuid(), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('high_price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('low_price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['last_ingestion_run_id'], ['ingestion_runs.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id', 'source_id', 'trading_date', name='uq_daily_price_listing_source_date')
    )
    op.create_index(op.f('ix_daily_price_bars_listing_id'), 'daily_price_bars', ['listing_id'], unique=False)
    op.create_index(op.f('ix_daily_price_bars_source_id'), 'daily_price_bars', ['source_id'], unique=False)
    op.create_index(op.f('ix_daily_price_bars_trading_date'), 'daily_price_bars', ['trading_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_price_bars_trading_date'), table_name='daily_price_bars')
    op.drop_index(op.f('ix_daily_price_bars_source_id'), table_name='daily_price_bars')
    op.drop_index(op.f('ix_daily_price_bars_listing_id'), table_name='daily_price_bars')
    op.drop_table('daily_price_bars')
    op.drop_index(op.f('ix_ingestion_runs_source_id'), table_name='ingestion_runs')
    op.drop_index(op.f('ix_ingestion_runs_listing_id'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
