"""add ranking snapshot readiness metadata

Revision ID: 8283d03a730d
Revises: 3bbb39cee74d
Create Date: 2026-09-20 18:44:32.890755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8283d03a730d'
down_revision: Union[str, Sequence[str], None] = '3bbb39cee74d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "ranking_snapshots",
    sa.Column(
        "status",
        sa.String(length=20),
        nullable=False,
        server_default="legacy",
    ),
    )
    op.add_column('ranking_snapshots', sa.Column('candidate_count', sa.Integer(), nullable=True))
    op.add_column('ranking_snapshots', sa.Column('ranked_company_count', sa.Integer(), nullable=True))
    op.add_column('ranking_snapshots', sa.Column('minimum_required_candidates', sa.Integer(), nullable=True))
    op.add_column('ranking_snapshots', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ranking_snapshots', sa.Column('approval_note', sa.Text(), nullable=True))
    op.create_index(op.f('ix_ranking_snapshots_status'), 'ranking_snapshots', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ranking_snapshots_status'), table_name='ranking_snapshots')
    op.drop_column('ranking_snapshots', 'approval_note')
    op.drop_column('ranking_snapshots', 'approved_at')
    op.drop_column('ranking_snapshots', 'minimum_required_candidates')
    op.drop_column('ranking_snapshots', 'ranked_company_count')
    op.drop_column('ranking_snapshots', 'candidate_count')
    op.drop_column('ranking_snapshots', 'status')
    # ### end Alembic commands ###
