"""add retrieval job planner

Revision ID: 8f52c1c99ae7
Revises: 27b612bf5a8f
Create Date: 2026-09-13 00:19:36.889879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f52c1c99ae7'
down_revision: Union[str, Sequence[str], None] = '27b612bf5a8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retrieval_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tracking_run_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('listing_id', sa.Uuid(), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('dataset_name', sa.String(length=100), nullable=False),
    sa.Column('required_start_date', sa.Date(), nullable=False),
    sa.Column('required_end_date', sa.Date(), nullable=False),
    sa.Column('full_history', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('ingestion_run_id', sa.Uuid(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['tracking_run_id'], ['tracking_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tracking_run_id', 'listing_id', 'provider_name', 'dataset_name', 'required_start_date', 'required_end_date', name='uq_retrieval_job_requirement')
    )
    op.create_index(op.f('ix_retrieval_jobs_company_id'), 'retrieval_jobs', ['company_id'], unique=False)
    op.create_index(op.f('ix_retrieval_jobs_listing_id'), 'retrieval_jobs', ['listing_id'], unique=False)
    op.create_index(op.f('ix_retrieval_jobs_status'), 'retrieval_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_retrieval_jobs_tracking_run_id'), 'retrieval_jobs', ['tracking_run_id'], unique=False)
    op.add_column('ingestion_runs', sa.Column('requested_start_date', sa.Date(), nullable=True))
    op.add_column('ingestion_runs', sa.Column('requested_end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingestion_runs', 'requested_end_date')
    op.drop_column('ingestion_runs', 'requested_start_date')
    op.drop_index(op.f('ix_retrieval_jobs_tracking_run_id'), table_name='retrieval_jobs')
    op.drop_index(op.f('ix_retrieval_jobs_status'), table_name='retrieval_jobs')
    op.drop_index(op.f('ix_retrieval_jobs_listing_id'), table_name='retrieval_jobs')
    op.drop_index(op.f('ix_retrieval_jobs_company_id'), table_name='retrieval_jobs')
    op.drop_table('retrieval_jobs')
    # ### end Alembic commands ###
