"""add company tracking tables

Revision ID: d236eb6c89f0
Revises: ebab23aa000d
Create Date: 2026-09-10 15:21:11.081634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd236eb6c89f0'
down_revision: Union[str, Sequence[str], None] = 'ebab23aa000d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracking_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('policy_name', sa.String(length=100), nullable=False),
    sa.Column('policy_hash', sa.String(length=64), nullable=False),
    sa.Column('policy_json', sa.JSON(), nullable=False),
    sa.Column('engine_version', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['ranking_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'policy_hash', 'engine_version', name='uq_tracking_run')
    )
    op.create_index(op.f('ix_tracking_runs_snapshot_id'), 'tracking_runs', ['snapshot_id'], unique=False)
    op.create_table('company_tracking_decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('main_universe', sa.Boolean(), nullable=False),
    sa.Column('elite_tracking', sa.Boolean(), nullable=False),
    sa.Column('elite_triggered_now', sa.Boolean(), nullable=False),
    sa.Column('first_elite_date', sa.Date(), nullable=True),
    sa.Column('historical_backfill_start', sa.Date(), nullable=True),
    sa.Column('dropout_tracking', sa.Boolean(), nullable=False),
    sa.Column('dropout_triggered_now', sa.Boolean(), nullable=False),
    sa.Column('dropout_until', sa.Date(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['tracking_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'company_id', name='uq_tracking_run_company')
    )
    op.create_index(op.f('ix_company_tracking_decisions_company_id'), 'company_tracking_decisions', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_tracking_decisions_run_id'), 'company_tracking_decisions', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_tracking_decisions_run_id'), table_name='company_tracking_decisions')
    op.drop_index(op.f('ix_company_tracking_decisions_company_id'), table_name='company_tracking_decisions')
    op.drop_table('company_tracking_decisions')
    op.drop_index(op.f('ix_tracking_runs_snapshot_id'), table_name='tracking_runs')
    op.drop_table('tracking_runs')
    # ### end Alembic commands ###
