"""create identity tables

Revision ID: daa8f9ff02c3
Revises: 
Create Date: 2026-09-10 03:38:20.569590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daa8f9ff02c3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_legal_name'), 'companies', ['legal_name'], unique=False)
    op.create_table('securities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('security_type', sa.String(length=50), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.CheckConstraint('end_date IS NULL OR start_date IS NULL OR end_date >= start_date', name='ck_security_date_range'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isin')
    )
    op.create_index(op.f('ix_securities_company_id'), 'securities', ['company_id'], unique=False)
    op.create_table('listings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('security_id', sa.Uuid(), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('exchange_code', sa.String(length=32), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name='ck_listing_date_range'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('security_id', 'exchange_code', 'ticker', 'start_date', name='uq_listing_period')
    )
    op.create_index(op.f('ix_listings_security_id'), 'listings', ['security_id'], unique=False)
    op.create_index(op.f('ix_listings_ticker'), 'listings', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listings_ticker'), table_name='listings')
    op.drop_index(op.f('ix_listings_security_id'), table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_securities_company_id'), table_name='securities')
    op.drop_table('securities')
    op.drop_index(op.f('ix_companies_legal_name'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
