"""add historical ranking tables

Revision ID: ebab23aa000d
Revises: daa8f9ff02c3
Create Date: 2026-09-10 03:54:12.395077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebab23aa000d'
down_revision: Union[str, Sequence[str], None] = 'daa8f9ff02c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ranking_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ranking_date', sa.Date(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('ranking_metric', sa.String(length=50), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('effective_date >= ranking_date', name='ck_ranking_snapshot_dates'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ranking_snapshots_ranking_date'), 'ranking_snapshots', ['ranking_date'], unique=False)
    op.create_table('company_rankings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('market_cap_usd', sa.Numeric(precision=30, scale=2), nullable=True),
    sa.CheckConstraint('rank > 0', name='ck_company_ranking_positive_rank'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['ranking_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'company_id', name='uq_snapshot_company'),
    sa.UniqueConstraint('snapshot_id', 'rank', name='uq_snapshot_rank')
    )
    op.create_index(op.f('ix_company_rankings_company_id'), 'company_rankings', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_rankings_snapshot_id'), 'company_rankings', ['snapshot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_rankings_snapshot_id'), table_name='company_rankings')
    op.drop_index(op.f('ix_company_rankings_company_id'), table_name='company_rankings')
    op.drop_table('company_rankings')
    op.drop_index(op.f('ix_ranking_snapshots_ranking_date'), table_name='ranking_snapshots')
    op.drop_table('ranking_snapshots')
    # ### end Alembic commands ###
